/*
 * Copyright (c) 2025 Huawei Device Co., Ltd. 2025-2025. ALL rights reserved.
 */

/**
 * Style Constants
 */
 export class StyleConst {
    /**
     * Full width.
     */
    public static readonly FULL_WIDTH: string = '100%';
    /**
     * Ninety percent width.
     */
    public static readonly NINETY_PERCENT_WIDTH: string = '90%';
    /**
     * Sixty percent width.
     */
    public static readonly SIXTY_PERCENT_WIDTH: string = '60%';
    /**
     * Thirty percent width.
     */
    public static readonly THIRTY_PERCENT_WIDTH: string = '30%';
    /**
     * Full height.
     */
    public static readonly FULL_HEIGHT: string = '100%';
    /**
     * Thirty percent height.
     */
    public static readonly THIRTY_PERCENT_HEIGHT: string = '30%';
    /**
     * Sixty percent height.
     */
    public static readonly SIXTY_PERCENT_HEIGHT: string = '60%';
    /**
     * Twenty five percent height.
     */
    public static readonly TWENTY_FIVE_PERCENT_HEIGHT: string = '25%';
    /**
     * Opacity.
     */
    public static readonly COMMON_OPACITY: number = 0.6;
    /**
     * Font weight.
     */
    public static readonly FONT_WIGHT_500: number = 500;
 }